import os
import re
import shutil
from pathlib import Path

"""
README /!\

This tool is currently in BETA stage.
It is NOT guaranteed to work correctly or be stable in all environments.

Use it at your own risk. Make sure to save your work before running or using this tool,
as unexpected behavior, bugs, or data loss may occur.

This file has been entirely generated by an AI system.

================================================================

License Notice:

Unlike the rest of this repository, this specific Python file is released under
the CC0 1.0 Universal (Public Domain Dedication).

You are free to copy, modify, distribute, and use this file for any purpose,
without asking for permission or providing attribution.

https://creativecommons.org/publicdomain/zero/1.0/

================================================================
"""

# ===== INPUT =====
BASE_DIR = Path(__file__).resolve().parent

OUTPUT_DIR = BASE_DIR / "gfx_sorted"

IMAGE_EXT = {".png", ".dds", ".tga"}

# ===== TAG =====
def detect_tag(filename: str):
    name = filename.upper()

    # 1. PRIORITY: TAG_XXX or XXX_
    m = re.search(r"\b([A-Z]{3})_", name)
    if m:
        return m.group(1)

    # 2. _TAG_ pattern (very common in mods)
    m = re.search(r"_([A-Z]{3})_", name)
    if m:
        return m.group(1)

    # 3. fallback: first valid HOI4 tag in filename
    m = re.search(r"\b([A-Z]{3})\b", name)
    if m:
        return m.group(1)

    return "UNK"


def safe_move(src: Path, dst: Path):
    dst.parent.mkdir(parents=True, exist_ok=True)

    if dst.exists():
        base = dst.stem
        ext = dst.suffix
        i = 1
        while dst.exists():
            dst = dst.with_name(f"{base}_{i}{ext}")
            i += 1

    shutil.move(str(src), str(dst))


def main():
    print(f"Scanning: {BASE_DIR}")

    OUTPUT_DIR.mkdir(exist_ok=True)

    count = 0

    for item in BASE_DIR.iterdir():
        if item.is_dir():
            continue

        if item.name == Path(__file__).name:
            continue

        if item.suffix.lower() not in IMAGE_EXT:
            continue

        tag = detect_tag(item.name)

        target = OUTPUT_DIR / tag / item.name

        safe_move(item, target)

        print(f"[{tag}] {item.name}")
        count += 1

    print("\n===== DONE =====")
    print(f"Files processed: {count}")
    print(f"Output folder: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()